"""Consistency audit between shipped results and manuscript claims.

Most checks use the numerical tables generated by the reproducible pipeline.
One targeted tau=10 propagation is rerun to verify the quoted decomposition of
excess energy into the immediate same-parity leakage channels. This is not a
full recomputation of the duration, temperature, or bias sweeps.
"""
from pathlib import Path
import json, math, re
import numpy as np
import pandas as pd
from engine import Engine, gibbs

ROOT = Path(__file__).resolve().parent
D = ROOT / "data"

def close(name, value, target, atol=0.0, rtol=0.0):
    if not np.isclose(value, target, atol=atol, rtol=rtol):
        raise AssertionError(f"{name}: got {value!r}, expected {target!r} (atol={atol}, rtol={rtol})")
    return value

def row(df, **conds):
    mask = np.ones(len(df), dtype=bool)
    for key, val in conds.items():
        if isinstance(val, float):
            mask &= np.isclose(df[key].astype(float), val)
        else:
            mask &= (df[key] == val)
    out = df[mask]
    if len(out) != 1:
        raise AssertionError(f"Expected one row for {conds}, found {len(out)}")
    return out.iloc[0]

def main():
    ref = json.loads((D / "reference.json").read_text())
    cal = pd.read_csv(D / "calibration.csv")
    pts = pd.read_csv(D / "selected_points.csv")
    slew = pd.read_csv(D / "slew_comparison.csv")
    dec = pd.read_csv(D / "bias_loss_decomposition.csv")
    cmp = pd.read_csv(D / "bias_tls_spatial_comparison.csv")
    tmap = pd.read_csv(D / "temperature_map.csv")
    prot = pd.read_csv(D / "protocols.csv")
    val = json.loads((D / "validation.json").read_text())

    # Reference endpoint / adiabatic-cycle numbers in the main text.
    close("J_o", ref["Jo"], 0.022477, atol=6e-7)
    close("J_c", ref["Jc"], 0.004414, atol=6e-7)
    close("W_ad", ref["W_ad"], 2.5315e-3, atol=6e-8)
    close("eta_ad", ref["eta"], 0.7899, atol=6e-5)

    # Same-parity gaps at open/closed endpoints.
    ro = cal.iloc[(cal["b"] - 0.5).abs().argmin()]
    rc = cal.iloc[(cal["b"] - 2.5).abs().argmin()]
    close("open even gap", ro.gap_even, 0.7625, atol=8e-5)
    close("open odd gap", ro.gap_odd, 1.0606, atol=8e-5)
    close("closed even gap", rc.gap_even, 1.0857, atol=8e-5)
    close("closed odd gap", rc.gap_odd, 1.1599, atol=8e-5)

    # Highlighted tau=10 quintic point.
    q10 = row(pts, protocol="smooth_b", tau=10.0)
    leak = q10.leakage_open + q10.leakage_close
    close("two-stroke leakage", leak, 2.8318e-3, atol=7e-8)
    close("leakage percent", 100 * leak, 0.283, atol=6e-4)
    lam = q10["bound"] / q10.W_ad
    close("Lambda", lam, 1.025, atol=6e-4)
    close("negative work at highlighted point", q10.W, -6.66e-5, atol=7e-8)
    close("bound saturation", q10["bound"] / (q10.D_open + q10.D_close), 0.9987, atol=2e-4)
    delta_bar = q10["bound"] / leak
    ellcrit = q10.W_ad / delta_bar
    close("leakage-weighted allowed gap", delta_bar, 0.9162, atol=8e-5)
    close("critical leakage fraction", ellcrit, 2.7629e-3, atol=8e-8)
    close("critical leakage percent", 100 * ellcrit, 0.276, atol=6e-4)


    # Transferability of the leakage scale across the four 41-duration sweeps.
    pp = prot.copy()
    pp["leak"] = pp.leakage_open + pp.leakage_close
    pp = pp[pp.leak > 0].copy()
    pp["delta_bar"] = pp["bound"] / pp.leak
    pp["ellcrit"] = pp.W_ad / pp.delta_bar
    close("sweep delta_bar minimum", pp.delta_bar.min(), 0.91578, atol=6e-5)
    close("sweep delta_bar maximum", pp.delta_bar.max(), 1.03789, atol=6e-5)
    close("sweep ellcrit minimum", pp.ellcrit.min(), 2.4391e-3, atol=8e-8)
    close("sweep ellcrit maximum", pp.ellcrit.max(), 2.7643e-3, atol=8e-8)

    crossing_ellcrit = []
    for protocol, g in pp.groupby("protocol"):
        g = g.sort_values("tau")
        signs = np.sign(g.W.to_numpy())
        for i in range(len(g) - 1):
            if g.W.iloc[i] <= 0 < g.W.iloc[i + 1]:
                crossing_ellcrit.extend([g.ellcrit.iloc[i], g.ellcrit.iloc[i + 1]])
                break
    close("crossing-bracket ellcrit minimum", min(crossing_ellcrit), 2.7286e-3, atol=8e-8)
    close("crossing-bracket ellcrit maximum", max(crossing_ellcrit), 2.7629e-3, atol=8e-8)

    # The lowest-cut tightness is not monotonic in duration.
    lj = prot[prot.protocol == "linear_J"].copy()
    lj["exact_loss"] = lj.D_open + lj.D_close
    lj["bound_fraction"] = lj["bound"] / lj.exact_loss
    sudden = lj.iloc[(lj.tau.abs()).argmin()]
    weakest = lj.iloc[lj.bound_fraction.argmin()]
    close("linear-J sudden bound fraction", sudden.bound_fraction, 0.71628, atol=6e-5)
    close("linear-J minimum bound fraction", weakest.bound_fraction, 0.57796, atol=6e-5)
    close("linear-J minimum-bound tau", weakest.tau, 63.23, atol=0.02)

    # Direct recomputation of the tau=10 channel decomposition quoted in the manuscript.
    eng = Engine()
    B10, D10 = eng.propagate(10.0, "smooth_b", columns=6)
    pc10 = gibbs(eng.ec, 0.01)
    ph10 = gibbs(eng.eo, 0.08)
    PB10 = np.abs(eng.R.T @ B10)**2
    PD10 = np.abs(D10)**2
    def channel_energy(mat, p0, ef):
        total = 0.0
        immediate = 0.0
        for n in (0, 1):
            for m in range(n + 2, eng.k, 2):
                x = p0[n] * (ef[m] - ef[n]) * mat[m, n]
                total += x
                if m == n + 2:
                    immediate += x
        return total, immediate
    to, io = channel_energy(PB10, pc10, eng.eo)
    tc, ic = channel_energy(PD10, ph10, eng.ec)
    immediate_fraction = (io + ic) / (to + tc)
    close("immediate same-parity excess-energy fraction", immediate_fraction, 0.9978, atol=6e-5)

    # Control-schedule statements.
    lj12 = row(pts, protocol="linear_J", tau=12.0)
    sp12 = row(pts, protocol="spectral_smooth", tau=12.0)
    close("linear-J work tau12", lj12.W, 1.5551e-3, atol=6e-8)
    close("spectral work tau12", sp12.W, 2.3903e-3, atol=6e-8)
    improvement = (sp12.W / lj12.W - 1) * 100
    close("tau12 work increase percent", improvement, 54.0, atol=0.4)

    lj20 = row(pts, protocol="linear_J", tau=20.0)
    sp20 = row(pts, protocol="spectral_smooth", tau=20.0)
    loss_lj20 = lj20.D_open + lj20.D_close
    loss_sp20 = sp20.D_open + sp20.D_close
    close("linear-J loss tau20", loss_lj20, 1.5977e-4, atol=7e-9)
    close("spectral loss tau20", loss_sp20, 3.7409e-6, atol=7e-10)
    close("loss reduction factor", loss_lj20 / loss_sp20, 43.0, atol=0.4)
    close("spectral recovered work percent", 100 * sp20.W / sp20.W_ad, 99.85, atol=0.02)

    eqspeed = slew[np.isclose(slew.vmax, 0.2)]
    es = row(eqspeed, protocol="spectral_smooth", vmax=0.2)
    ej = row(eqspeed, protocol="linear_J", vmax=0.2)
    eb = row(eqspeed, protocol="linear_b", vmax=0.2)
    close("spectral equal-speed work", es.W, 2.526e-3, atol=8e-7)
    close("spectral equal-speed tau", es.tau, 21.39, atol=0.02)
    close("linear-J equal-speed work", ej.W, 2.312e-3, atol=8e-7)
    close("linear-J equal-speed tau", ej.tau, 30.48, atol=0.02)
    if not eb.W < 0:
        raise AssertionError("linear-b equal-peak-speed point should be non-engine")

    # Full-spatial vs projected biased-doublet statements.
    d01 = row(dec, eps_over_Jo=0.1, tau=20.0)
    d04 = row(dec, eps_over_Jo=0.4, tau=20.0)
    close("eps=.1 within-doublet loss", d01.internal_total, 1.96e-4, atol=8e-7)
    close("eps=.1 higher-state loss", d01.leak_energy_total, 1.20e-4, atol=8e-7)
    close("eps=.4 within-doublet loss", d04.internal_total, 2.39e-3, atol=8e-6)
    close("eps=.4 higher-state loss", d04.leak_energy_total, 1.19e-4, atol=8e-7)

    sym10 = row(cmp, eps_over_Jo=0.0, tau=10.0)
    sym20 = row(cmp, eps_over_Jo=0.0, tau=20.0)
    sym40 = row(cmp, eps_over_Jo=0.0, tau=40.0)
    close("symmetric spatial W/Wad tau10", sym10.Wnorm_spatial, -0.026, atol=7e-4)
    close("symmetric spatial W/Wad tau20", sym20.Wnorm_spatial, 0.952, atol=7e-4)
    close("symmetric spatial W/Wad tau40", sym40.Wnorm_spatial, 0.9997, atol=7e-5)
    subset = cmp[np.isclose(cmp.tau, 40.0) & (cmp.eps_over_Jo <= 0.4 + 1e-12)]
    max_pp = 100 * np.max(np.abs(subset.delta_Wnorm))
    if max_pp > 1.1 + 0.02:
        raise AssertionError(f"Projected/full-spatial mismatch at tau=40 exceeds 1.1 pp: {max_pp}")

    # Reduced-time schedule slopes quoted in the control comparison.
    u = np.linspace(0.0, 1.0, 20001)
    expected_rms = {"linear_J": 2.36, "linear_b": 2.00, "smooth_b": 2.39, "spectral_smooth": 2.48}
    for kind, target in expected_rms.items():
        bb = np.array([float(eng.barrier(x, kind)) for x in u])
        dbdu = np.gradient(bb, u)
        rms = np.sqrt(np.trapezoid(dbdu**2, u))
        close(f"RMS slope {kind}", rms, target, atol=0.006)

    # Operating-map detection fraction quoted in the Fig. 3 caption.
    for protocol, expected_nonengine, expected_detected in [("linear_J", 350, 337), ("spectral_smooth", 404, 404)]:
        d = tmap[tmap.protocol == protocol].copy()
        nonengine = d.W <= 0
        detected = (d["bound"] / d.W_ad >= 1) & nonengine
        false_positive = ((d["bound"] / d.W_ad >= 1) & (d.W > 0)).sum()
        if int(nonengine.sum()) != expected_nonengine or int(detected.sum()) != expected_detected:
            raise AssertionError(f"temperature-map detection counts changed for {protocol}")
        if int(false_positive) != 0:
            raise AssertionError(f"temperature-map false positive found for {protocol}")

    # Physical-unit mapping printed in Discussion.
    hbar = 1.054571817e-34
    echarge = 1.602176634e-19
    u = 1.66053906660e-27
    m_be9 = 9.0121831 * u
    f0 = 200e3
    omega0 = 2 * np.pi * f0
    x0 = np.sqrt(hbar / (m_be9 * omega0))
    sep = 2 * 2.4 * x0
    width = 0.5 * x0
    split_o = 2 * ref["Jo"] * f0
    split_c = 2 * ref["Jc"] * f0
    tw = 20 / omega0
    eps_dimless = 0.1 * ref["Jo"]
    field = eps_dimless * hbar * omega0 / (echarge * sep)
    close("x0 nm", x0 * 1e9, 74.9, atol=0.2)
    close("well separation nm", sep * 1e9, 359, atol=1.0)
    close("Gaussian width nm", width * 1e9, 37, atol=0.6)
    close("open tunnel splitting kHz", split_o / 1e3, 8.99, atol=0.02)
    close("closed tunnel splitting kHz", split_c / 1e3, 1.77, atol=0.02)
    close("tau20 microseconds", tw * 1e6, 15.9, atol=0.1)
    close("0.1Jo field microV/m", field * 1e6, 5.0, atol=0.3)

    if val.get("status") != "PASS":
        raise AssertionError("data/validation.json is not PASS")

    print("PAPER CONSISTENCY CHECK: PASS")
    print(f"  highlighted leakage = {100*leak:.4f}%")
    print(f"  Lambda = {lam:.6f}")
    print(f"  critical leakage estimate = {100*ellcrit:.4f}%")
    print(f"  sweep ellcrit range = {pp.ellcrit.min():.6g} to {pp.ellcrit.max():.6g}")
    print(f"  crossing-bracket ellcrit range = {min(crossing_ellcrit):.6g} to {max(crossing_ellcrit):.6g}")
    print(f"  immediate-channel loss fraction at tau=10 = {100*immediate_fraction:.3f}%")
    print(f"  tau=20 loss reduction = {loss_lj20/loss_sp20:.2f}x")
    print(f"  max projected/full-spatial mismatch at tau=40, eps<=0.4Jo = {max_pp:.3f} percentage points")
    print(f"  illustrative 0.1Jo field = {field*1e6:.3f} microV/m")

if __name__ == "__main__":
    main()
