"""Fast consistency audit between shipped numerical tables and manuscript claims.

This does not rerun the expensive spatial propagation. It checks the numerical
results already generated by the reproducible pipeline and fails if the values
used in the manuscript drift beyond their stated rounding.
"""
from pathlib import Path
import json, math, re
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent
D = ROOT / "data"

def close(name, value, target, atol=0.0, rtol=0.0):
    if not np.isclose(value, target, atol=atol, rtol=rtol):
        raise AssertionError(f"{name}: got {value!r}, expected {target!r} (atol={atol}, rtol={rtol})")
    return value

def row(df, **conds):
    mask = np.ones(len(df), dtype=bool)
    for key, val in conds.items():
        if isinstance(val, float):
            mask &= np.isclose(df[key].astype(float), val)
        else:
            mask &= (df[key] == val)
    out = df[mask]
    if len(out) != 1:
        raise AssertionError(f"Expected one row for {conds}, found {len(out)}")
    return out.iloc[0]

def main():
    ref = json.loads((D / "reference.json").read_text())
    cal = pd.read_csv(D / "calibration.csv")
    pts = pd.read_csv(D / "selected_points.csv")
    slew = pd.read_csv(D / "slew_comparison.csv")
    dec = pd.read_csv(D / "bias_loss_decomposition.csv")
    cmp = pd.read_csv(D / "bias_tls_spatial_comparison.csv")
    val = json.loads((D / "validation.json").read_text())

    # Reference endpoint / adiabatic-cycle numbers in the main text.
    close("J_o", ref["Jo"], 0.022477, atol=6e-7)
    close("J_c", ref["Jc"], 0.004414, atol=6e-7)
    close("W_ad", ref["W_ad"], 2.5315e-3, atol=6e-8)
    close("eta_ad", ref["eta"], 0.7899, atol=6e-5)

    # Same-parity gaps at open/closed endpoints.
    ro = cal.iloc[(cal["b"] - 0.5).abs().argmin()]
    rc = cal.iloc[(cal["b"] - 2.5).abs().argmin()]
    close("open even gap", ro.gap_even, 0.7625, atol=8e-5)
    close("open odd gap", ro.gap_odd, 1.0606, atol=8e-5)
    close("closed even gap", rc.gap_even, 1.0857, atol=8e-5)
    close("closed odd gap", rc.gap_odd, 1.1599, atol=8e-5)

    # Highlighted tau=10 quintic point.
    q10 = row(pts, protocol="smooth_b", tau=10.0)
    leak = q10.leakage_open + q10.leakage_close
    close("two-stroke leakage", leak, 2.8318e-3, atol=7e-8)
    close("leakage percent", 100 * leak, 0.283, atol=6e-4)
    lam = q10["bound"] / q10.W_ad
    close("Lambda", lam, 1.025, atol=6e-4)
    close("negative work at highlighted point", q10.W, -6.66e-5, atol=7e-8)
    close("bound saturation", q10["bound"] / (q10.D_open + q10.D_close), 0.9987, atol=2e-4)

    # Control-schedule statements.
    lj12 = row(pts, protocol="linear_J", tau=12.0)
    sp12 = row(pts, protocol="spectral_smooth", tau=12.0)
    close("linear-J work tau12", lj12.W, 1.5551e-3, atol=6e-8)
    close("spectral work tau12", sp12.W, 2.3903e-3, atol=6e-8)
    improvement = (sp12.W / lj12.W - 1) * 100
    close("tau12 work increase percent", improvement, 54.0, atol=0.4)

    lj20 = row(pts, protocol="linear_J", tau=20.0)
    sp20 = row(pts, protocol="spectral_smooth", tau=20.0)
    loss_lj20 = lj20.D_open + lj20.D_close
    loss_sp20 = sp20.D_open + sp20.D_close
    close("linear-J loss tau20", loss_lj20, 1.5977e-4, atol=7e-9)
    close("spectral loss tau20", loss_sp20, 3.7409e-6, atol=7e-10)
    close("loss reduction factor", loss_lj20 / loss_sp20, 43.0, atol=0.4)
    close("spectral recovered work percent", 100 * sp20.W / sp20.W_ad, 99.85, atol=0.02)

    eqspeed = slew[np.isclose(slew.vmax, 0.2)]
    es = row(eqspeed, protocol="spectral_smooth", vmax=0.2)
    ej = row(eqspeed, protocol="linear_J", vmax=0.2)
    eb = row(eqspeed, protocol="linear_b", vmax=0.2)
    close("spectral equal-speed work", es.W, 2.526e-3, atol=8e-7)
    close("spectral equal-speed tau", es.tau, 21.39, atol=0.02)
    close("linear-J equal-speed work", ej.W, 2.312e-3, atol=8e-7)
    close("linear-J equal-speed tau", ej.tau, 30.48, atol=0.02)
    if not eb.W < 0:
        raise AssertionError("linear-b equal-peak-speed point should be non-engine")

    # Full-spatial vs projected biased-doublet statements.
    d01 = row(dec, eps_over_Jo=0.1, tau=20.0)
    d04 = row(dec, eps_over_Jo=0.4, tau=20.0)
    close("eps=.1 within-doublet loss", d01.internal_total, 1.96e-4, atol=8e-7)
    close("eps=.1 higher-state loss", d01.leak_energy_total, 1.20e-4, atol=8e-7)
    close("eps=.4 within-doublet loss", d04.internal_total, 2.39e-3, atol=8e-6)
    close("eps=.4 higher-state loss", d04.leak_energy_total, 1.19e-4, atol=8e-7)

    sym10 = row(cmp, eps_over_Jo=0.0, tau=10.0)
    sym20 = row(cmp, eps_over_Jo=0.0, tau=20.0)
    sym40 = row(cmp, eps_over_Jo=0.0, tau=40.0)
    close("symmetric spatial W/Wad tau10", sym10.Wnorm_spatial, -0.026, atol=7e-4)
    close("symmetric spatial W/Wad tau20", sym20.Wnorm_spatial, 0.952, atol=7e-4)
    close("symmetric spatial W/Wad tau40", sym40.Wnorm_spatial, 0.9997, atol=7e-5)
    subset = cmp[np.isclose(cmp.tau, 40.0) & (cmp.eps_over_Jo <= 0.4 + 1e-12)]
    max_pp = 100 * np.max(np.abs(subset.delta_Wnorm))
    if max_pp > 1.1 + 0.02:
        raise AssertionError(f"Projected/full-spatial mismatch at tau=40 exceeds 1.1 pp: {max_pp}")

    # Physical-unit mapping printed in Discussion.
    hbar = 1.054571817e-34
    echarge = 1.602176634e-19
    u = 1.66053906660e-27
    m_be9 = 9.0121831 * u
    f0 = 200e3
    omega0 = 2 * np.pi * f0
    x0 = np.sqrt(hbar / (m_be9 * omega0))
    sep = 2 * 2.4 * x0
    width = 0.5 * x0
    split_o = 2 * ref["Jo"] * f0
    split_c = 2 * ref["Jc"] * f0
    tw = 20 / omega0
    eps_dimless = 0.1 * ref["Jo"]
    field = eps_dimless * hbar * omega0 / (echarge * sep)
    close("x0 nm", x0 * 1e9, 74.9, atol=0.2)
    close("well separation nm", sep * 1e9, 359, atol=1.0)
    close("Gaussian width nm", width * 1e9, 37, atol=0.6)
    close("open tunnel splitting kHz", split_o / 1e3, 8.99, atol=0.02)
    close("closed tunnel splitting kHz", split_c / 1e3, 1.77, atol=0.02)
    close("tau20 microseconds", tw * 1e6, 15.9, atol=0.1)
    close("0.1Jo field microV/m", field * 1e6, 5.0, atol=0.3)

    if val.get("status") != "PASS":
        raise AssertionError("data/validation.json is not PASS")

    print("PAPER CONSISTENCY CHECK: PASS")
    print(f"  highlighted leakage = {100*leak:.4f}%")
    print(f"  Lambda = {lam:.6f}")
    print(f"  tau=20 loss reduction = {loss_lj20/loss_sp20:.2f}x")
    print(f"  max projected/full-spatial mismatch at tau=40, eps<=0.4Jo = {max_pp:.3f} percentage points")
    print(f"  illustrative 0.1Jo field = {field*1e6:.3f} microV/m")

if __name__ == "__main__":
    main()
